name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer poetry
        run: pip install poetry

      - name: Installer les dépendances
        run: poetry install

      - name: Exécuter les tests avec couverture
        run: poetry run pytest --cov=Games Test
